apiVersion: v1
description: Provides easy monitoring definitions for Kubernetes services, and deployment
  and management of Prometheus instances.
maintainers:
- email: mgoodness@gmail.com
  name: Michael Goodness
name: prometheus-operator
sources:
- https://github.com/coreos/prometheus-operator
version: 0.2.0
